---
- name: Install and configure Nginx on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update APT package cache (with detailed logging)
      ansible.builtin.apt:
        update_cache: true
      become: true
      register: apt_update_result
      failed_when: apt_update_result is failed
      ignore_errors: true

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
