---
- name: Orchestrate the deployment of Docker, Flask, and Nginx
  hosts: all

- name: Install Docker
  ansible.builtin.import_playbook: install_docker.yaml

- name: Deploy Flask App Container
  ansible.builtin.import_playbook: deploy_flask.yaml

- name: Install and Configure Nginx
  ansible.builtin.import_playbook: deploy_nginx.yaml

- name: Install and Configure Nginx
  ansible.builtin.import_playbook: remove_nginx_default.yaml
