name: CI/CD Pipeline for Terraform and Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manually triggering the workflow
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/aws_instance
          chmod 600 ~/.ssh/aws_instance

      - name: Set up SSH public key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/aws_instance.pub
          chmod 600 ~/.ssh/aws_instance.pub

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/stage

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/stage

      # - name: Generate Inventory
      #   run: |
      #     terraform output -json ec2_ips | jq -r '.[]' | awk '{print "[ec2]\n" $1}' > ../ansible/inventory/inventory.ini
      #   working-directory: ./terraform/stage

      - name: Commit and push inventory.ini
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ansible/inventory/inventory.ini
          git commit -m "Update dynamic inventory"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Install Ansible collection
        run: |
          ansible-galaxy role install -r collections/requirements.yml
          ansible-galaxy collection install -r collections/requirements.yml
        working-directory: ./ansible

      - name: Install Ansible role
        run: |
          ansible-galaxy role install -r collections/requirements.yml
        working-directory: ./ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ./playbooks/main_deploy.yaml -i ./inventory/inventory.ini -i ./inventory/inventory.ini
        working-directory: ./ansible
